_target_: dementia_agent.knowledge_graph.graph.PersonData
name: Nora
age: 31
node_type: ${get_object:dementia_agent.knowledge_graph.graph.NodeType.PERSON}
misc:
    description: Nora is one of the nurses working at the elderly care home.