_target_: dementia_agent.knowledge_graph.graph.PersonData
name: Margaret Doe
age: 86
node_type: ${get_object:dementia_agent.knowledge_graph.graph.NodeType.PERSON}
misc:
    description: this is the user, an elder suffering from dementia.