_target_: dementia_agent.knowledge_graph.graph.EventData
title: Death of Arthur Doe
location: ''
time: ''
day: ''
description: The death of Arthur Doe, a traumatic experience for the family.
node_type: ${get_object:dementia_agent.knowledge_graph.graph.NodeType.EVENT}