_target_: dementia_agent.knowledge_graph.graph.EventData
title: Morning Coffee
location: Living Room
time: '10:00 AM'
day: Monday
description: On a normal Monday, the user usually drinks coffee in the living room to start the day with Jane.
node_type: ${get_object:dementia_agent.knowledge_graph.graph.NodeType.EVENT}